### ISSUE TITLE
Way to provide client implementation through DI

### ISSUE THREAD

**Issue by simPod** [spawnia/sailor#10]
_First of all, thank you for this project. Finally had a time to look at it and use it and it looks pretty solid!_

I was looking for a way to provide a custom client implementation to query calls. Let's say I'd like to specify a curl implementation for my prod and dev env and mock implementation for my test env.

I have a service that is calling an endpoint generated by this library:

`Query::execute()`

How can I provide a mock client from certain test case? Thanks.

```php
public function testService() {
     $c = new ClientMock('expected response');
     $s = new Service();
     // how to pass $c?
     self::assertSth($s->run());
}
```

**Comment by simPod** [comment]
My first idea was to return Response template from EndpointConfig instead of client. Then generate query classes with ClientInterface in constructor that would allow me to inject them using DI.

**Comment by spawnia** [comment]
```php
Configuration::setEndpointConfigMap([
    'endpoint-to-mock' => $mockEndpoint,
]);
```

**Comment by spawnia** [comment]
This can certainly be made better and/or documented :)

**Comment by simPod** [comment]
Thanks! Would you be open in changing the lib so generated classes can be be injected through DI? Or should I rather leverage those singletons through `Configuration`?

**Comment by spawnia** [comment]
I don't know how that would look like, can you propose a PR?
