### ISSUE TITLE
Allow setting HTTP headers per request

### ISSUE THREAD

**Issue by mintbridge** [spawnia/sailor#23]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to set headers as part of the request, they can only be done as part of the client config, so any dynamic header, including authorisation is impossible unless i'm missing something?

**Describe the solution you'd like**
Along with variables (or as part of them?) be able to set http headers on the client at the point of making the request

**Describe alternatives you've considered**
Injecting a dynamic client, but some things are request dependant so it didnt really work.

Im happy to pull something together for it if you think its something that would be included?

**Comment by spawnia** [comment]
Can you provide details for an actual use case where headers must be set per request?

**Comment by spawnia** [comment]
I would like to avoid adding additional arguments to the generated `Operation::execute()` method, since that could clash with the generated arguments. We could use something like a builder pattern:

```php
MyQuery
    ::withOptions(['headers' => ...])
    ->execute(1, 'asdf');
```

The actual client implementation is decoupled by an interface though, which currently only requires a single `request()` method. I wonder how we would extend that, can we have a one-size-fits-all implementation? Do we need to restructure that completely?

**Comment by mintbridge** [comment]
Yeah i had a play with adding arguments to `Operation::execute()` and it got complex real quick. The builder option looks like it could be a nice though, will have a play with that

We use headers for a few things, adding context about the user so that infrastructure can route things, but the main pain point is that we call a downstream graphql endpoint as the user that is logged in an set the authorization header to be the users token

**Comment by spawnia** [comment]
https://github.com/spawnia/sailor/releases/tag/v0.10.0 solves this.

### Dynamic clients

You can configure clients dynamically for specific operations or per request:

```php
/** @var \Spawnia\Sailor\Client $client Somehow instantiated dynamically */
\Example\Api\HelloSailor::setClient($client);

// Will use $client over the client from EndpointConfig
$result = HelloSailor::execute();

// Reverts to using the client from EndpointConfig
HelloSailor::setClient(null);
