### ISSUE TITLE
Allow other HTTP Client Implementations

### ISSUE THREAD

**Issue by Lappihuan** [spawnia/sailor#26]
This Library is very intresting!
Thank you for the effort so far.

**Is your feature request related to a problem? Please describe.**

We are currently already using Symfony HttpClient and with this library we would add Guzzle as another dependency.
It would be great if one could provide the client of their choice to sailor.

**Describe the solution you'd like**

As far as i know, sailor should require a PSR-18? Interface instead of the Guzzle Client directly.

**Comment by spawnia** [comment]
Your client only needs to implement https://github.com/spawnia/sailor/blob/aa1f3a1a1a08861896286da71742dacbb16f969f/src/Client.php

**Comment by Lappihuan** [comment]
But that will still install guzzle as a dependency.

**Comment by spawnia** [comment]
Got you. I agree that keeping dependencies minimal is a good idea, so I went ahead and made `guzzle/guzzle` optional.
