### ISSUE TITLE
Handle Exception that isClientSafe()

### ISSUE THREAD

**Issue by SimBig** [spawnia/sailor#46]
**Is your feature request related to a problem? Please describe.**

If the server throws a client safe exception ( `isClientSafe() === true`) there should be a way to handle/recognize this appropriately.

**Describe the solution you'd like**

The exception that was client-safe on the origin-server should be forwarded as `isClientSafe() === true` to the client through the intermediate-server/caller

**Describe alternatives you've considered**

- A config file that indicates how client safe exceptions should be handled
- a per-request configuration that indicates how client safe exceptions should be handled on this request

**Comment by spawnia** [comment]
The concept of client safe exceptions is just an implementation detail of some GraphQL servers and has no structured representation in the actually transmitted error response. Sailor should work with any server, thus all it can build upon is the [error response specification](http://spec.graphql.org/October2021/#sec-Errors). The only guaranteed contents of an error is a string under the key `message`.

That said, servers can expose structured data to errors through extensions. We can ease the transformation of generic errors to structured error objects through a per-endpoint configuration.
