### ISSUE TITLE
Allow to introspect but not generate classes

### ISSUE THREAD

**Issue by simPod** [spawnia/sailor#53]
I'm using IDE gql plugin to generate schema definitions. However, Sailor does this better.

I'd like to use sailor for introspection only in some cases. That said to be able to run introspect but not to generate classes.

I propose to introduce SchemaConfig class.

**Comment by spawnia** [comment]
There is `vendor/bin/sailor introspect` - is that not sufficient?

**Comment by simPod** [comment]
But `vendor/bin/sailor` generates hundreds of files I don't need then.

**Comment by spawnia** [comment]
Why are you calling it then?

**Comment by simPod** [comment]
To generate classes for apis I want to be generated.

My example app is having like 10 apis that I want to have sailor classes be generated for and then there are like 4 apis I want only schema introspection from.

**Comment by spawnia** [comment]
I see, that makes sense.

**Comment by simPod** [comment]
I wonder that for simplicity I could have two configuration files. So if we
allow to specify e.g. `-c` flag, that would suffice.

Vendor bin sailor -c nointrospect.php

Wdyt? That would not introduce more complexity.

**Comment by spawnia** [comment]
`-c/--config` option seems suitable, and indeed a much simpler solution!
