### ISSUE TITLE
Keywords as field or type names

### ISSUE THREAD

**Issue by spawnia** [spawnia/sailor#63]
**Describe the bug**

![image](https://user-images.githubusercontent.com/12158000/164037880-32f378cb-a066-44a7-8bc6-f2140f5bd4b1.png)

**Expected behavior/Solution**

Notify the user about this conflict instead of silently failing.

See https://www.php.net/manual/en/reserved.php

**Steps to reproduce**

1. Query a schema with a field name such as `print` or `int`

**Comment by simPod** [comment]
I have encountered similar issue where I run codegen over a schema with `type Switch`.

Sailor tries to create `class Switch` which is not a valid class name.
